## Import Library

In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier

## Membagi data train dan test

In [2]:
ecoli_imbalance = pd.read_csv("../dataset/ecoli.csv")
ecoli_imbalance

     Unnamed: 0        name   mcg   gvh   lip  chg   aac  alm1  alm2 class
0             0   AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35    cp
1             1  ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44    cp
2             2  ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46    cp
3             3  ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36    cp
4             4   ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35    cp
..          ...         ...   ...   ...   ...  ...   ...   ...   ...   ...
331         331  TREA_ECOLI  0.74  0.56  0.48  0.5  0.47  0.68  0.30    pp
332         332  UGPB_ECOLI  0.71  0.57  0.48  0.5  0.48  0.35  0.32    pp
333         333  USHA_ECOLI  0.61  0.60  0.48  0.5  0.44  0.39  0.38    pp
334         334  XYLF_ECOLI  0.59  0.61  0.48  0.5  0.42  0.42  0.37    pp
335         335  YTFQ_ECOLI  0.74  0.74  0.48  0.5  0.31  0.53  0.52    pp

[336 rows x 10 columns]

## Fitur Dan Target

Fitur: 
- mcg
- gvh
- lip 
- chg
- chg
- aac
- alm1
- alm2

Target:  
- class

In [3]:
fitur = ["mcg", "gvh", "lip", "chg", "aac", "alm1", "alm2"]
target = ["class"]

## Pemisahan Data
data training: **80%**  
data test: **20%**

In [4]:
X = ecoli_imbalance[fitur]
y = ecoli_imbalance[target]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
data_train = X_train.merge(y_train, left_index=True, right_index=True)
data_train

      mcg   gvh   lip  chg   aac  alm1  alm2 class
60   0.44  0.56  0.48  0.5  0.50  0.46  0.54    cp
227  0.69  0.43  0.48  0.5  0.59  0.74  0.77   imU
322  0.62  0.78  0.48  0.5  0.47  0.49  0.54    pp
318  0.66  0.71  0.48  0.5  0.41  0.50  0.35    pp
17   0.44  0.27  0.48  0.5  0.55  0.52  0.58    cp
..    ...   ...   ...  ...   ...   ...   ...   ...
188  0.12  0.43  0.48  0.5  0.63  0.70  0.74    im
71   0.44  0.51  0.48  0.5  0.47  0.26  0.36    cp
106  0.44  0.49  0.48  0.5  0.39  0.38  0.40    cp
270  0.56  0.68  0.48  0.5  0.77  0.36  0.45    om
102  0.38  0.26  0.48  0.5  0.54  0.16  0.28    cp

[268 rows x 8 columns]

In [6]:
data_test = X_test.merge(y_test, left_index=True, right_index=True)
data_test

      mcg   gvh   lip  chg   aac  alm1  alm2 class
72   0.37  0.50  0.48  0.5  0.42  0.36  0.45    cp
110  0.32  0.33  0.48  0.5  0.60  0.06  0.20    cp
298  0.64  0.72  0.48  0.5  0.49  0.42  0.19    pp
108  0.49  0.43  0.48  0.5  0.49  0.30  0.40    cp
277  0.71  0.71  0.48  0.5  0.68  0.43  0.36    om
..    ...   ...   ...  ...   ...   ...   ...   ...
299  0.68  0.82  0.48  0.5  0.38  0.65  0.56    pp
295  0.71  0.71  0.48  0.5  0.40  0.54  0.39    pp
328  0.69  0.66  0.48  0.5  0.41  0.50  0.25    pp
84   0.36  0.56  0.48  0.5  0.43  0.45  0.53    cp
245  0.47  0.46  0.48  0.5  0.62  0.74  0.77   imU

[68 rows x 8 columns]

## Klasifikasi menggunakan Naive Bayes

In [7]:
naive_bayes_model = GaussianNB()
naive_bayes_model.fit(X_train, y_train)
y_pred = naive_bayes_model.predict(X_test)
print(y_pred)

['cp' 'cp' 'pp' 'cp' 'pp' 'cp' 'im' 'omL' 'im' 'cp' 'im' 'cp' 'cp' 'cp'
 'cp' 'im' 'im' 'im' 'cp' 'cp' 'im' 'cp' 'cp' 'pp' 'cp' 'cp' 'cp' 'pp'
 'im' 'cp' 'im' 'pp' 'pp' 'pp' 'cp' 'pp' 'im' 'pp' 'cp' 'pp' 'cp' 'cp'
 'imU' 'im' 'cp' 'pp' 'pp' 'cp' 'im' 'cp' 'cp' 'im' 'im' 'cp' 'pp' 'cp'
 'cp' 'im' 'cp' 'cp' 'cp' 'cp' 'im' 'pp' 'pp' 'pp' 'cp' 'im']

C:\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [8]:
akurasi = accuracy_score(y_test, y_pred)
laporan_klasifikasi = classification_report(y_test, y_pred)
print(f"Akurasi Model Naive Bayes: {akurasi:.2f}")
print("\nLaporan Klasifikasi:")
print(laporan_klasifikasi)

Akurasi Model Naive Bayes: 0.72

Laporan Klasifikasi:
              precision    recall  f1-score   support

          cp       0.91      0.94      0.92        32
          im       0.59      0.77      0.67        13
         imS       0.00      0.00      0.00         1
         imU       0.00      0.00      0.00         4
          om       0.00      0.00      0.00         6
         omL       1.00      1.00      1.00         1
          pp       0.50      0.73      0.59        11

    accuracy                           0.72        68
   macro avg       0.43      0.49      0.45        68
weighted avg       0.64      0.72      0.67        68

C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Klasifikasi dengan RandomForest

In [9]:
random_forest_model = RandomForestClassifier()
random_forest_model.fit(X_train, y_train)

C:\Python312\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [10]:
y_pred_random_forest = random_forest_model.predict(X_test)
akurasi_random_forest = accuracy_score(y_test, y_pred_random_forest)
laporan_random_forest = classification_report(y_test, y_pred_random_forest)

print(f"Akurasi: {akurasi_random_forest:.2f}")
print("Laporan random forest: \n", laporan_random_forest)

C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Akurasi: 0.88
Laporan random forest:
               precision    recall  f1-score   support

          cp       0.91      0.97      0.94        32
          im       0.83      0.77      0.80        13
         imS       0.00      0.00      0.00         1
         imU       0.75      0.75      0.75         4
          om       1.00      1.00      1.00         6
         omL       1.00      1.00      1.00         1
          pp       0.82      0.82      0.82        11

    accuracy                           0.88        68
   macro avg       0.76      0.76      0.76        68
weighted avg       0.87      0.88      0.87        68

## Bagging dengan Naive Bayes estimator

In [11]:
bagging_nb = BaggingClassifier(n_estimators=100, estimator=GaussianNB())
bagging_nb.fit(X_train, y_train)

C:\Python312\Lib\site-packages\sklearn\ensemble\_bagging.py:888: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

BaggingClassifier(estimator=GaussianNB(), n_estimators=100)

In [12]:
y_pred_bagging_nb = bagging_nb.predict(X_test)
akurasi_bagging_nb = accuracy_score(y_test, y_pred_bagging_nb)
laporan_bagging_nb = classification_report(y_test, y_pred_bagging_nb)
print(f"Akurasi: {akurasi_random_forest:.2f}")
print("Laporan random forest: \n", laporan_bagging_nb)

Akurasi: 0.88
Laporan random forest:
               precision    recall  f1-score   support

          cp       0.91      0.94      0.92        32
          im       0.59      0.77      0.67        13
         imS       0.00      0.00      0.00         1
         imU       0.00      0.00      0.00         4
          om       1.00      0.33      0.50         6
         omL       1.00      1.00      1.00         1
          pp       0.57      0.73      0.64        11

    accuracy                           0.75        68
   macro avg       0.58      0.54      0.53        68
weighted avg       0.74      0.75      0.72        68

C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\naive_bayes.py:509: RuntimeWarning: divide by zero encountered in log
  jointi = np.log(self.class_prior_[i])
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Bagging menggunakan DecissionTree estimator

In [13]:
bagging_dt = BaggingClassifier(n_estimators=100, estimator=DecisionTreeClassifier())
bagging_dt.fit(X_train, y_train)

C:\Python312\Lib\site-packages\sklearn\ensemble\_bagging.py:888: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=100)

In [14]:
y_pred_bagging_dt = bagging_dt.predict(X_test)
akurasi_bagging_dt = accuracy_score(y_test, y_pred_bagging_dt)
laporan_bagging_dt = classification_report(y_test, y_pred_bagging_dt)
print(f"Akurasi: {akurasi_random_forest:.2f}")
print("Laporan random forest: \n", laporan_bagging_nb)

Akurasi: 0.88
Laporan random forest:
               precision    recall  f1-score   support

          cp       0.91      0.94      0.92        32
          im       0.59      0.77      0.67        13
         imS       0.00      0.00      0.00         1
         imU       0.00      0.00      0.00         4
          om       1.00      0.33      0.50         6
         omL       1.00      1.00      1.00         1
          pp       0.57      0.73      0.64        11

    accuracy                           0.75        68
   macro avg       0.58      0.54      0.53        68
weighted avg       0.74      0.75      0.72        68

C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))